### ISSUE TITLE
Bug: plugin wont load

### ISSUE THREAD

**Issue by Diorb22** [Chicken/BlueMap-Towny#10]
hi,i have an issue with your plugin, when i try to use it my console says:

[Server] Server thread/ERROR Could not load 'plugins/BlueMap-Towny-2.0.0.jar' in folder 'plugins'

is there a possible fix?

**Comment by Chicken** [comment]
try 2.1.0? also what server platform are you running and on what version

**Comment by Diorb22** [comment]
i am running spigot on 1.17 and i have both bluemap and towny installed

**Comment by Diorb22** [comment]
so what i should do?

**Comment by Chicken** [comment]
did you try 2.1.0...?

**Comment by Chicken** [comment]
also please switch from spigot to paper
