### ISSUE TITLE
Bug: 2.1.0.jar gives wrong version (2.0.1) in console

### ISSUE THREAD

**Issue by illyrius666** [Chicken/BlueMap-Towny#11]
**Description of the bug**

21.03 07:59:49 [Server] [WARN] [BlueMap-Towny] New version available: v2.1.0 (current: v2.0.1)
21.03 07:59:49 [Server] [WARN] [BlueMap-Towny] Download it at https://github.com/Chicken/BlueMap-Towny/releases/latest

**Reproducing**

Steps to produce the issue:
1. Put the BlueMap-Towny-2.1.0.jar in the plugins folder and run the server.
2. Go to the console and keep an eye on it.
3. You will see the error popping up.

**Expected behavior**

Not show the error since the version with the jar should match.

**Comment by Chicken** [comment]
Ok I have no idea how I've blundered that but I've now updated the release with the correct jar file
