### ISSUE TITLE
Bug: Economy runtime thread error - Severe server performance issue

### ISSUE THREAD

**Issue by Firav** [Chicken/BlueMap-Towny#6]
**Description of the bug**

Looks like the script is bugging out about retrieving economy placeholders.
https://pastebin.com/YzWNiP9v

**Reproducing**

Steps to produce the issue:
1. Install plugins
2. Load server

**Versions**

Paper: 1.20.1-R0.1-SNAP git-Paper-81
Towny: 0.100.0.14
Vault: v1.7.3-b131
BlueMap-Towny: 2.0.1
GoldBank: 1.17-2.0

**Comment by Firav** [comment]
Would there be any timeline for a resolve to this issue?

**Comment by Chicken** [comment]
totally forgor ill check it out over the weekend, the pastebin has expired, could you pls reupload to https://haste.antti.codes

**Comment by Firav** [comment]
https://haste.antti.codes/uquvusikez.yaml

**Comment by Chicken** [comment]
Welp this is awkward, I installed the plugins, made a town, put some balance in there and uhh... it works?  
BlueMap-Towny is just merely calling the `town.getAccount()` method, so I don't think I'm doing anything wrong.  
Looking at your logs it seems like everything is fine to be honest, is it just getting stuck on disk I/O

**Comment by Chicken** [comment]
Idk but here's a version that runs stuff in another thread. If it is somehow BlueMap-Towny's fault it shouldn't at least crash the server.
https://antti.pics/f/BzNsqQ

**Comment by Firav** [comment]
> Welp this is awkward, I installed the plugins, made a town, put some balance in there and uhh... it works? BlueMap-Towny is just merely calling the `town.getAccount()` method, so I don't think I'm doing anything wrong. Looking at your logs it seems like everything is fine to be honest, is it just getting stuck on disk I/O

Huh, strange! This host we run off is SSD/NVME, so its not a hardware throttle. Sounds almost like a process throttle. Let me try that version you posted and get back to you with some results.

**Comment by Chicken** [comment]
Just for the record- how many towns does the server have?

**Comment by Firav** [comment]
Not a terrible amount. 81 towns and 7 nations.
Towny seems to have an issue with running large econ jobs a well. Takes it a bit to return results from `/t list by balance`. The only reason that it doesn't cause hell is because that command is run on an async thread.

**Comment by Firav** [comment]
> Idk but here's a version that runs stuff in another thread. If it is somehow BlueMap-Towny's fault it shouldn't at least crash the server. https://antti.pics/f/BzNsqQ

This version of the plugin seems to be working as intended now. No longer getting those thread hangs or large stack errors from delayed threads.

**Comment by Chicken** [comment]
Added to git in 2783c9f4c9a300b0ad66bf10451021c4310bc42f releasing properly soon
