### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by PrototypeError** [Chicken/BlueMap-Towny#7]
Hey, I would like to be able to set permission for using /t map color and /t n color

I searched a lot but did not find anywhere if it exists or not. I actually did not find any perms. If there are any I'm sorry for bothering you. If not I would like to request it as a feature.

Goal:
Permission for /t set mapcolor

**Comment by Chicken** [comment]
`towny.command.town.set.mapcolor` and `towny.command.nation.set.mapcolor`
